"""added repo column

Revision ID: 231a2111e700
Revises: 
Create Date: 2015-05-03 15:10:52.598113

"""

# revision identifiers, used by Alembic.
revision = '231a2111e700'
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('issue_snapshots', sa.Column('repo', sa.String(length=1024), nullable=True, default='7Geese'))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('issue_snapshots', 'repo')
    ### end Alembic commands ###
