"""added users table

Revision ID: 3cc300fbe337
Revises: 231a2111e700
Create Date: 2015-05-07 23:09:29.679479

"""

# revision identifiers, used by Alembic.
revision = '3cc300fbe337'
down_revision = '231a2111e700'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=1024), nullable=True),
    sa.Column('access_token', sa.String(length=1024), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    ### end Alembic commands ###
